# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800ceb8d76a79af9e0b4f5dcf54abae2b85a9debd9f911afa3ba3bf929ac18ea516250477b151e1b29f02f0747378da2430034422d8acf5fa74d7f0915848770

test:
  secret_key_base: 5ac7374e577b566f3f1d982c1435cf68b5425466569ddaf96a94ccea09771b39778a6e8bb24263f0ebc13c39b43b3785bff7639e02a857e4af843c320341a31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
